#!/usr/bin/env node
// mcp-tools.mjs - public/mcp-tools.json from worker/tools.ts (the CLI proxy's shape:
// { tools: [{ name, description, inputSchema }] }). node --experimental-strip-types.
import { writeFileSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const { DOCS_TOOLS } = await import(join(root, "worker", "tools.ts"));
writeFileSync(join(root, "public", "mcp-tools.json"), JSON.stringify({
  _note: "GENERATED by scripts/mcp-tools.mjs from worker/tools.ts: the free tools the docs /mcp serves (https://docs.despia.com/mcp). Proxy these as they are.",
  endpoint: "https://docs.despia.com/mcp",
  tools: DOCS_TOOLS.map((t) => ({ name: t.name, description: t.description,
    inputSchema: { type: "object", properties: t.inputs, required: t.required ?? [], additionalProperties: false } })),
}, null, 2) + "\n");
console.log(`[docs.mcp-tools] ${DOCS_TOOLS.length} tool(s) -> public/mcp-tools.json`);
