#!/usr/bin/env node
//
//  redirects.mjs - every old docs URL keeps working, in ONE 301 hop. Generated, never typed:
//  the inputs are the live inventory of setup.despia.com (redirects/inventory/, one row per
//  page of the old Mintlify sitemap) and the ported legacy tree (content/legacy/).
//
//  Outputs (all under redirects/, nothing is deployed from here):
//    setup.despia.com.csv        Cloudflare Bulk Redirects list: source_url,target_url,status_code,
//                                preserve_query_string,include_subdomains,subpath_matching,
//                                preserve_path_suffix. One row per page, its .md sibling, the root,
//                                llms.txt / llms-full.txt / sitemap.xml (exact rows; a list cannot
//                                hold the catch-all beside the root row, the Worker form does).
//    setup-worker/index.js       the same table as a tiny Worker (route: setup.despia.com/*), for a
//                                zone that prefers a Worker to a Bulk Redirect list
//    setup-worker/wrangler.jsonc its manifest (no account id; `wrangler deploy` is the owner's call)
//    docs-root.json              docs.despia.com's own old-root behaviour: a v3 path asked of the
//                                new root (it used to bounce to setup.despia.com) 301s to /legacy/...
//                                when no modern page owns that path. worker/index.ts imports it.
//

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const siteCfg = JSON.parse(readFileSync(join(root, "data", "site.json"), "utf8"));
const DOCS = `${siteCfg.origin}${siteCfg.base}`; // https://despia.com/docs (owner 2026-10-10), was docs.despia.com
const out = join(root, "redirects");

const inventory = readFileSync(join(out, "inventory", "setup.despia.com.tsv"), "utf8").split("\n").slice(1)
  .map((line) => line.split("\t")).filter((cols) => cols[0] === "setup.despia.com").map((cols) => cols[1]);

const legacyDir = join(root, "content", "legacy");
if (!existsSync(legacyDir)) {
  console.error("[docs.redirects] content/legacy missing - run `npm run compile` first");
  process.exit(1);
}
function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => e.isDirectory() ? walk(join(dir, e.name))
    : e.name.endsWith(".md") ? [join(dir, e.name)] : []);
}
const legacyPaths = walk(legacyDir).map((f) => "/" + relative(legacyDir, f).split(sep).join("/").replace(/\.md$/, "")).sort();
const legacySet = new Set(legacyPaths);

const missing = inventory.filter((p) => !legacySet.has(p));
if (missing.length > 0) {
  console.error(`[docs.redirects] ${missing.length} live setup.despia.com page(s) have no ported page: ${missing.join(", ")}`);
  process.exit(1);
}

// ── the setup.despia.com table: exact rows first, catch-all last ──────────────────────────
const rows = [];
const add = (from, to) => rows.push({ from, to });
add("/", `${DOCS}/legacy/introduction`);
for (const p of legacyPaths) {
  add(p, `${DOCS}/legacy${p}`);
  add(`${p}.md`, `${DOCS}/legacy${p}.md`);
}
add("/llms.txt", `${DOCS}/legacy/llms.txt`);
add("/llms-full.txt", `${DOCS}/legacy/llms-full.txt`);
add("/sitemap.xml", `${DOCS}/sitemap.xml`);

const csv = [
  "source_url,target_url,status_code,preserve_query_string,include_subdomains,subpath_matching,preserve_path_suffix",
  // exact rows only: a list holds one row per source URL, so the path-preserving catch-all
  // (any path v3 never listed -> the same path under /legacy) lives in the Worker form
  ...rows.map((r) => `setup.despia.com${r.from},${r.to},301,TRUE,FALSE,FALSE,FALSE`),
].join("\n") + "\n";
writeFileSync(join(out, "setup.despia.com.csv"), csv);

const table = Object.fromEntries(rows.map((r) => [r.from, r.to]));
mkdirSync(join(out, "setup-worker"), { recursive: true });
writeFileSync(join(out, "setup-worker", "index.js"), `//
//  GENERATED by scripts/redirects.mjs - do not edit; regenerate.
//  setup.despia.com (the v3 Mintlify docs) -> docs.despia.com/legacy, one 301 per request.
//  Exact table first (${rows.length} rows: every page, its .md sibling, the root, llms.txt,
//  llms-full.txt, sitemap.xml); anything else keeps its path under /legacy. Case is preserved,
//  a trailing slash is dropped, the query string rides along.
//
const DOCS = ${JSON.stringify(DOCS)};
const TABLE = ${JSON.stringify(table)};

export function target(url) {
  const u = new URL(url);
  let path = u.pathname;
  if (path.length > 1 && path.endsWith("/")) path = path.replace(/\\/+$/, "");
  const to = TABLE[path] ?? \`\${DOCS}/legacy\${path}\`;
  return to + u.search;
}

export default {
  fetch(request) {
    return Response.redirect(target(request.url), 301);
  },
};
`);
writeFileSync(join(out, "setup-worker", "wrangler.jsonc"), `// GENERATED by scripts/redirects.mjs. The setup.despia.com redirect Worker. Not deployed by
// any script in this repo: attaching the route is the DNS cutover the owner approves.
{
  "name": "despia-setup-redirects",
  "main": "index.js",
  "compatibility_date": "2025-08-01",
  "routes": [{ "pattern": "setup.despia.com/*", "zone_name": "despia.com" }],
  "workers_dev": false
}
`);

// ── docs.despia.com old-root behaviour ────────────────────────────────────────────────────
const config = JSON.parse(readFileSync(join(root, "dsx.config.json"), "utf8"));
const modernRoutes = new Set(config.routes.map((r) => r.path));
const rootTable = {};
let shadowed = 0;
for (const p of legacyPaths) {
  if (modernRoutes.has(p)) { shadowed += 1; continue; }
  rootTable[p] = `/legacy${p}`;
  rootTable[`${p}.md`] = `/legacy${p}.md`;
}
// Mintlify-era Modern API paths and the catalog aliases (redirects/modern-aliases.json): one 301 to the page that took
// each over. A target must be a page of this build; a source must not be one.
const aliases = JSON.parse(readFileSync(join(out, "modern-aliases.json"), "utf8")).aliases;
for (const [from, to] of Object.entries(aliases)) {
  if (modernRoutes.has(from)) { console.error(`[docs.redirects] alias ${from} shadows a page`); process.exit(1); }
  rootTable[from] = to;
  if (!to.includes("#")) rootTable[`${from}.md`] = `${to}.md`;
}
// Despia V4 docs v2 (redirects/v2-moves.json): the pages that moved get one 301 each, and every target above that
// points at a moved page is sent straight to the new address (one hop, never a chain).
const v2 = JSON.parse(readFileSync(join(out, "v2-moves.json"), "utf8"));
const moveTarget = (to) => {
  if (v2.moves[to] !== undefined) return v2.moves[to];
  const [page, anchor] = to.split("#");
  const md = page.endsWith(".md") ? page.slice(0, -3) : null;
  if (md !== null && v2.moves[md] !== undefined && !v2.moves[md].startsWith("http")) return `${v2.moves[md]}.md`;
  if (v2.moves[page] !== undefined) return v2.moves[page];
  for (const [prefix, dest] of Object.entries(v2.prefixes)) if (page.startsWith(prefix)) return dest;
  return anchor === undefined ? to : to;
};
for (const [from, to] of Object.entries(rootTable)) rootTable[from] = moveTarget(to);
for (const from of Object.keys(aliases)) {
  const page = rootTable[from].split("#")[0];
  if (!modernRoutes.has(page) && !page.startsWith("/legacy/") && !page.startsWith("http")) console.warn(`[docs.redirects] alias ${from} -> ${rootTable[from]}: no such page in this build`);
}
for (const [from, to] of Object.entries(v2.moves)) {
  if (from.includes("#")) continue;
  rootTable[from] = to;
  if (!to.startsWith("http")) rootTable[`${from}.md`] = `${to}.md`;
}
writeFileSync(join(out, "docs-root.json"), JSON.stringify(rootTable, null, 1) + "\n");

console.log(`[docs.redirects] setup.despia.com: ${rows.length} exact row(s) (Worker adds the catch-all; ${inventory.length}/${inventory.length} live pages covered) -> redirects/setup.despia.com.csv, redirects/setup-worker/; docs root: ${Object.keys(rootTable).length / 2} v3 path(s) -> /legacy (${shadowed} owned by a modern page)`);
