#!/usr/bin/env node
//
//  sync-skills.mjs - the agent skills pages' source (owner 2026-10-10): every folder of OpenSource/AgentSkills in the
//  framework repository becomes one page, generated, never hand written. Writes
//    data/skills.json                   name, description, files, mirrored (in the public pack today), source commit
//    public/skills/<name>/SKILL.md      the exact file, served for "Download SKILL.md" (the Worker sends it as an attachment)
//  The public pack is despia-native/skills (OpenSource/AgentSkills/mirror.json `repo`). A skill is `mirrored` when the
//  public repository's head holds its folder (checked with a shallow clone into a temp folder).
//    DESPIA_FRAMEWORK=<clone> [DESPIA_FRAMEWORK_REF=origin/dev] node scripts/sync-skills.mjs
//

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repo = process.env.DESPIA_FRAMEWORK;
const ref = process.env.DESPIA_FRAMEWORK_REF ?? "origin/dev";
if (!repo) { console.error("[docs.sync-skills] set DESPIA_FRAMEWORK"); process.exit(1); }
const git = (...args) => execFileSync("git", ["-C", repo, ...args], { encoding: "utf8", maxBuffer: 64 << 20 });
const commit = git("rev-parse", ref).trim();
const BASE = "OpenSource/AgentSkills";
const mirror = JSON.parse(git("show", `${commit}:${BASE}/mirror.json`));

const tree = git("ls-tree", "-r", "--name-only", commit, BASE).split("\n").filter(Boolean);
const names = [...new Set(tree.map((p) => p.slice(BASE.length + 1)).filter((p) => p.includes("/")).map((p) => p.split("/")[0]))].sort();

// what the public pack holds today
let published = new Set();
const tmp = mkdtempSync(join(tmpdir(), "despia-skills-"));
try {
  execFileSync("git", ["clone", "-q", "--depth", "1", `https://github.com/${mirror.repo}.git`, join(tmp, "pack")], { stdio: "ignore" });
  published = new Set(readdirSync(join(tmp, "pack"), { withFileTypes: true }).filter((e) => e.isDirectory() && !e.name.startsWith(".")).map((e) => e.name));
} catch { console.warn(`[docs.sync-skills] could not read ${mirror.repo}; every skill is marked not yet public`); }
finally { rmSync(tmp, { recursive: true, force: true }); }

const out = join(root, "public", "skills");
rmSync(out, { recursive: true, force: true });
const skills = names.map((name) => {
  const files = tree.filter((p) => p.startsWith(`${BASE}/${name}/`)).map((p) => p.slice(BASE.length + name.length + 2));
  const text = git("show", `${commit}:${BASE}/${name}/SKILL.md`);
  const fm = /^---\n([\s\S]*?)\n---/.exec(text)?.[1] ?? "";
  const field = (k) => (new RegExp(`^${k}:\\s*(.*)$`, "m").exec(fm)?.[1] ?? "").trim().replace(/^"(.*)"$/, "$1");
  mkdirSync(join(out, name), { recursive: true });
  writeFileSync(join(out, name, "SKILL.md"), text);
  return { name: field("name") || name, folder: name, description: field("description"), files, mirrored: published.has(name) };
});
writeFileSync(join(root, "data", "skills.json"), JSON.stringify({ _note: "GENERATED by scripts/sync-skills.mjs. Regenerate, never edit.", source: { ref, commit }, repo: mirror.repo, skills }, null, 1) + "\n");
console.log(`[docs.sync-skills] ${skills.length} skill(s) from ${ref} ${commit.slice(0, 10)}; ${skills.filter((s) => s.mirrored).length} in the public pack ${mirror.repo}`);
